{"uuid":"9079b867-034f-4459-b9f9-aff5cebb43f2","historyId":"b4dc32724d6ecda85c0bff89ec73529a","fullName":"Test.Tap.Tap_Bahrain.Visa_Bahrain_Tap","labels":[{"name":"package","value":"Test.Tap.Tap_Bahrain"},{"name":"testClass","value":"Test.Tap.Tap_Bahrain"},{"name":"testMethod","value":"Visa_Bahrain_Tap"},{"name":"parentSuite","value":"Default Suite"},{"name":"suite","value":"payment"},{"name":"subSuite","value":"Test.Tap.Tap_Bahrain"},{"name":"host","value":"JIT-Meltantawi.local"},{"name":"thread","value":"8974@JIT-Meltantawi.local.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"}],"links":[],"name":"Visa_Bahrain_Tap","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"Database Action \"CreateConnection\" failed. With the following test data \"jdbc:postgresql://dev-database-v2.csm6dywjcf4g.eu-central-1.rds.amazonaws.com:5432/payment_qa\". Root cause: \"org.postgresql.util.PSQLException: Connection attempt timed out.\"","trace":"java.lang.AssertionError: Database Action \"CreateConnection\" failed. With the following test data \"jdbc:postgresql://dev-database-v2.csm6dywjcf4g.eu-central-1.rds.amazonaws.com:5432/payment_qa\". Root cause: \"org.postgresql.util.PSQLException: Connection attempt timed out.\"\n\tat org.testng.Assert.fail(Assert.java:99)\n\tat com.shaft.tools.io.internal.FailureReporter.fail(FailureReporter.java:38)\n\tat com.shaft.db.DatabaseActions.failAction(DatabaseActions.java:94)\n\tat com.shaft.db.DatabaseActions.failAction(DatabaseActions.java:247)\n\tat com.shaft.db.DatabaseActions.createConnection(DatabaseActions.java:468)\n\tat com.shaft.db.DatabaseActions.executeSelectQuery(DatabaseActions.java:353)\n\tat Test.Tap.Tap_Bahrain.Visa_Bahrain_Tap(Tap_Bahrain.java:64)\n\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:578)\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)\n\tat org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)\n\tat org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)\n\tat org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)\n\tat org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1511)\n\tat org.testng.TestRunner.privateRun(TestRunner.java:848)\n\tat org.testng.TestRunner.run(TestRunner.java:621)\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:443)\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:336)\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1200)\n\tat org.testng.TestNG.runSuites(TestNG.java:1114)\n\tat org.testng.TestNG.run(TestNG.java:1082)\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)\nCaused by: org.postgresql.util.PSQLException: Connection attempt timed out.\n\tat org.postgresql.Driver$ConnectThread.getResult(Driver.java:359)\n\tat org.postgresql.Driver.connect(Driver.java:271)\n\tat java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)\n\tat java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)\n\tat com.shaft.db.DatabaseActions.createConnection(DatabaseActions.java:461)\n\t... 27 more\n"},"stage":"finished","steps":[{"name":"Perform POST request to https://payment-api.qa.svc.jahez.net/api/app/payment-order","status":"passed","stage":"finished","steps":[{"name":" Assert that objects are equal","status":"passed","stage":"finished","steps":[{"name":"Assertion Passed: Evaluating that the response is successful (Status code is between 200 and 299).","status":"passed","stage":"finished","steps":[],"attachments":[{"name":"Screenshot - 1702662959608_Visa_Bahrain_Tap_ValidateEquals_passed","source":"b168f3f4-4880-495d-a239-2bd6d928341f-attachment.png","type":"image/png"}],"parameters":[{"name":"customLog","value":"Assertion Passed: Evaluating that the response is successful (Status code is between 200 and 299)."},{"name":"attachments","value":"[[Screenshot, 1702662959608_Visa_Bahrain_Tap_ValidateEquals_passed, java.io.ByteArrayInputStream@5b82e090]]"}],"start":1702662961225,"stop":1702662961235}],"attachments":[],"parameters":[],"start":1702662959361,"stop":1702662961236},{"name":"Request details:  \"POST | Target Status Code: 0 | Service URL: https://payment-api.qa.svc.jahez.net/api/app/payment-order | Content Type: application/json | Response Time: 4739ms\".","status":"passed","stage":"finished","steps":[],"attachments":[{"name":"API Request - Specifications","source":"dd6cf250-259e-4db8-98cb-18152578a8f0-attachment"},{"name":"API Request - Body","source":"462c1d4a-7fec-45f9-bd6d-0f6960775d39-attachment"},{"name":"API Response - JSON Body","source":"a95f276f-202d-4b23-ae92-2ebb1f5a93be-attachment.json","type":"text/json"}],"parameters":[{"name":"logText","value":"Request details:  \"POST | Target Status Code: 0 | Service URL: https://payment-api.qa.svc.jahez.net/api/app/payment-order | Content Type: application/json | Response Time: 4739ms\"."},{"name":"attachments","value":"[[API Request, Specifications, Headers:\n_______________\n\nAccept-Language=en\n__tenant=3a070412-6c55-04e0-3ee5-e2438d7a5765\nContent-Type=application/json\n\n], [API Request, Body, java.io.ByteArrayInputStream@2d05291f], null, [API Response, JSON Body, java.io.ByteArrayInputStream@2f9739e0]]"},{"name":"status","value":"PASS"}],"start":1702662961263,"stop":1702662961352}],"attachments":[],"parameters":[],"start":1702662954520,"stop":1702662961352},{"name":"Navigate to url \"https://payment-blazor.qa.svc.jahez.net/payment/NVwvLUlWsw?culture=en&__tenant=3a070412-6c55-04e0-3ee5-e2438d7a5765\".","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1702662982726,"stop":1702662982726},{"name":"Type \"4508750015741019\" into \"By.xpath: //input[@id='card_input_mini']\".","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1702662993028,"stop":1702662993028},{"name":"Type \"01/39\" into \"Payments\".","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1702662993123,"stop":1702662993123},{"name":"Type \"100\" into \"logo\".","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1702662993196,"stop":1702662993196},{"name":"Click \"PAY\".","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1702662993373,"stop":1702662993373},{"name":"Click \"By.xpath: //input[@type='submit']\".","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1702663015147,"stop":1702663015147},{"name":"Database Action \"CreateConnection\" failed. With the following test data \"jdbc:postgresql://dev-database-v2.csm6dywjcf4g.eu-central-1.rds.amazonaws.com:5432/payment_qa\".","status":"passed","statusDetails":{"known":false,"muted":false,"flaky":false,"trace":"org.postgresql.util.PSQLException: Connection attempt timed out.\n org.postgresql.Driver$ConnectThread.getResult(Driver.java:359)\n org.postgresql.Driver.connect(Driver.java:271)\n java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)\n java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)\n com.shaft.db.DatabaseActions.createConnection(DatabaseActions.java:461)\n com.shaft.db.DatabaseActions.executeSelectQuery(DatabaseActions.java:353)\n Test.Tap.Tap_Bahrain.Visa_Bahrain_Tap(Tap_Bahrain.java:64)\n java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)\n java.base/java.lang.reflect.Method.invoke(Method.java:578)\n org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)\n org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)\n org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)\n org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)\n org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)\n org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)\n org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)\n org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)\n java.base/java.util.ArrayList.forEach(ArrayList.java:1511)\n org.testng.TestRunner.privateRun(TestRunner.java:848)\n org.testng.TestRunner.run(TestRunner.java:621)\n org.testng.SuiteRunner.runTest(SuiteRunner.java:443)\n org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)\n org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)\n org.testng.SuiteRunner.run(SuiteRunner.java:336)\n org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\n org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\n org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)\n org.testng.TestNG.runSuitesLocally(TestNG.java:1200)\n org.testng.TestNG.runSuites(TestNG.java:1114)\n org.testng.TestNG.run(TestNG.java:1082)\n com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)\n com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)"},"stage":"finished","steps":[],"attachments":[{"name":"Database Action Exception - CreateConnection - Stacktrace","source":"6c345b41-16fc-4355-85c4-08dcb8247ccd-attachment"}],"parameters":[{"name":"logText","value":"Database Action \"CreateConnection\" failed. With the following test data \"jdbc:postgresql://dev-database-v2.csm6dywjcf4g.eu-central-1.rds.amazonaws.com:5432/payment_qa\"."},{"name":"attachments","value":"[[Database Action Exception - CreateConnection, Stacktrace, org.postgresql.util.PSQLException: Connection attempt timed out.\n org.postgresql.Driver$ConnectThread.getResult(Driver.java:359)\n org.postgresql.Driver.connect(Driver.java:271)\n java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)\n java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)\n com.shaft.db.DatabaseActions.createConnection(DatabaseActions.java:461)\n com.shaft.db.DatabaseActions.executeSelectQuery(DatabaseActions.java:353)\n Test.Tap.Tap_Bahrain.Visa_Bahrain_Tap(Tap_Bahrain.java:64)\n java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)\n java.base/java.lang.reflect.Method.invoke(Method.java:578)\n org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)\n org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)\n org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)\n org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)\n org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)\n org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)\n org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)\n org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)\n java.base/java.util.ArrayList.forEach(ArrayList.java:1511)\n org.testng.TestRunner.privateRun(TestRunner.java:848)\n org.testng.TestRunner.run(TestRunner.java:621)\n org.testng.SuiteRunner.runTest(SuiteRunner.java:443)\n org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)\n org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)\n org.testng.SuiteRunner.run(SuiteRunner.java:336)\n org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\n org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\n org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)\n org.testng.TestNG.runSuitesLocally(TestNG.java:1200)\n org.testng.TestNG.runSuites(TestNG.java:1114)\n org.testng.TestNG.run(TestNG.java:1082)\n com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)\n com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)\n]]"},{"name":"status","value":"FAIL"}],"start":1702663075341,"stop":1702663075342},{"name":"Database Action \"CreateConnection\" failed. With the following test data \"jdbc:postgresql://dev-database-v2.csm6dywjcf4g.eu-central-1.rds.amazonaws.com:5432/payment_qa\". Root cause: \"org.postgresql.util.PSQLException: Connection attempt timed out.\"","status":"passed","statusDetails":{"known":false,"muted":false,"flaky":false,"trace":"org.postgresql.util.PSQLException: Connection attempt timed out.\n org.postgresql.Driver$ConnectThread.getResult(Driver.java:359)\n org.postgresql.Driver.connect(Driver.java:271)\n java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)\n java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)\n com.shaft.db.DatabaseActions.createConnection(DatabaseActions.java:461)\n com.shaft.db.DatabaseActions.executeSelectQuery(DatabaseActions.java:353)\n Test.Tap.Tap_Bahrain.Visa_Bahrain_Tap(Tap_Bahrain.java:64)\n java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)\n java.base/java.lang.reflect.Method.invoke(Method.java:578)\n org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)\n org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)\n org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)\n org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)\n org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)\n org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)\n org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)\n org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)\n java.base/java.util.ArrayList.forEach(ArrayList.java:1511)\n org.testng.TestRunner.privateRun(TestRunner.java:848)\n org.testng.TestRunner.run(TestRunner.java:621)\n org.testng.SuiteRunner.runTest(SuiteRunner.java:443)\n org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)\n org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)\n org.testng.SuiteRunner.run(SuiteRunner.java:336)\n org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\n org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\n org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)\n org.testng.TestNG.runSuitesLocally(TestNG.java:1200)\n org.testng.TestNG.runSuites(TestNG.java:1114)\n org.testng.TestNG.run(TestNG.java:1082)\n com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)\n com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)"},"stage":"finished","steps":[],"attachments":[{"name":"Database actions - Get  stack  trace - Exception Stacktrace","source":"29c8d71a-811b-4fc0-8f7d-c76dd9c94906-attachment"}],"parameters":[{"name":"logText","value":"Database Action \"CreateConnection\" failed. With the following test data \"jdbc:postgresql://dev-database-v2.csm6dywjcf4g.eu-central-1.rds.amazonaws.com:5432/payment_qa\". Root cause: \"org.postgresql.util.PSQLException: Connection attempt timed out.\""},{"name":"attachments","value":"[[Database actions - Get  stack  trace, Exception Stacktrace, org.postgresql.util.PSQLException: Connection attempt timed out.\n org.postgresql.Driver$ConnectThread.getResult(Driver.java:359)\n org.postgresql.Driver.connect(Driver.java:271)\n java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)\n java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)\n com.shaft.db.DatabaseActions.createConnection(DatabaseActions.java:461)\n com.shaft.db.DatabaseActions.executeSelectQuery(DatabaseActions.java:353)\n Test.Tap.Tap_Bahrain.Visa_Bahrain_Tap(Tap_Bahrain.java:64)\n java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)\n java.base/java.lang.reflect.Method.invoke(Method.java:578)\n org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)\n org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)\n org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)\n org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)\n org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)\n org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)\n org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)\n org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)\n java.base/java.util.ArrayList.forEach(ArrayList.java:1511)\n org.testng.TestRunner.privateRun(TestRunner.java:848)\n org.testng.TestRunner.run(TestRunner.java:621)\n org.testng.SuiteRunner.runTest(SuiteRunner.java:443)\n org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)\n org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)\n org.testng.SuiteRunner.run(SuiteRunner.java:336)\n org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\n org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\n org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)\n org.testng.TestNG.runSuitesLocally(TestNG.java:1200)\n org.testng.TestNG.runSuites(TestNG.java:1114)\n org.testng.TestNG.run(TestNG.java:1082)\n com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)\n com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)\n]]"},{"name":"status","value":"FAIL"}],"start":1702663075343,"stop":1702663075344}],"attachments":[{"name":"SHAFT Engine Logs - Current Method log: Visa_Bahrain_Tap","source":"c2756020-3ed1-43fe-8489-6dd27d744cbd-attachment.txt","type":"text/plain"}],"parameters":[],"start":1702662954507,"stop":1702663075348}